# Generated by Django 4.2.7 on 2024-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default_profile_image.png', max_length=400, null=True, upload_to='image/'),
        ),
    ]
