# Generated by Django 4.2.7 on 2024-02-17 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Role',
            field=models.CharField(default='Recruiter', max_length=255),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=150, null=True)),
                ('alt_mobile', models.CharField(blank=True, max_length=150, null=True)),
                ('position', models.CharField(blank=True, max_length=150, null=True)),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('client_location', models.CharField(blank=True, max_length=150, null=True)),
                ('project_director', models.CharField(blank=True, max_length=150, null=True)),
                ('project_partner', models.CharField(blank=True, max_length=150, null=True)),
                ('fees', models.CharField(blank=True, max_length=150, null=True)),
                ('employee_status', models.CharField(blank=True, max_length=20, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('start_date_of_work_order', models.DateField(blank=True, null=True)),
                ('end_date_of_work_order', models.DateField(blank=True, null=True)),
                ('work_order_detail', models.CharField(blank=True, max_length=150, null=True)),
                ('upload_work_order', models.FileField(blank=True, null=True, upload_to='work_order/')),
                ('upload_nda', models.FileField(blank=True, null=True, upload_to='nda/')),
                ('upload_resume', models.FileField(blank=True, null=True, upload_to='employeeresume/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
