# Generated by Django 4.2.7 on 2024-02-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0002_customuser_role_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Role',
            new_name='role',
        ),
    ]
