# Generated by Django 4.2.7 on 2024-01-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0004_alter_profile_user_alter_skill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
